<a href="https://colab.research.google.com/github/SLane35/EntityMatching/blob/master/EntityMatching.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
try:
    import deepmatcher
except:
    !pip install git+https://github.com/anhaidgroup/deepmatcher.git


  Cloning https://github.com/anhaidgroup/deepmatcher.git to /tmp/pip-req-build-f1cyth9g
  Running command git clone -q https://github.com/anhaidgroup/deepmatcher.git /tmp/pip-req-build-f1cyth9g
     |████████████████████████████████| 71kB 2.5MB/s 
  Created wheel for deepmatcher: filename=deepmatcher-0.1.1-py2.py3-none-any.whl size=55003 sha256=9bd63c624d88843d47dc19cf17b0a1467c2319356ae7f845b204572eadbb7249
  Stored in directory: /tmp/pip-ephem-wheel-cache-amcav9sd/wheels/21/b3/11/dc933837985fcb4683f016ed48f88ae73f90f9b20c122fbedd
  Created wheel for fasttext: filename=fasttext-0.9.2-cp36-cp36m-linux_x86_64.whl size=3015955 sha256=3d6557ba518961061baf75e0196588e79ef3c0375b72a47e446978696a2c2299
  Stored in directory: /root/.cache/pip/wheels/98/ba/7f/b154944a1cf5a8cee91c154b75231136cc3a3321ab0e30f592
Successfully built deepmatcher fasttext


In [ ]:
import deepmatcher as dm

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
try:
  import recordlinkage
except:
  !pip install -qqq recordlinkage

     |████████████████████████████████| 952kB 3.2MB/s 
     |████████████████████████████████| 102kB 6.0MB/s 


In [ ]:
import pandas as pd
import recordlinkage
from recordlinkage.datasets import load_febrl1
df = load_febrl1(True)

In [ ]:
dfNoLabels = load_febrl1()


In [ ]:
matching_dictionary = df[1]

In [ ]:
left_df = dfNoLabels.loc[matching_dictionary.get_level_values(0)]

In [ ]:
right_df = dfNoLabels.loc[matching_dictionary.get_level_values(1)]

In [ ]:
left_df

given_name     surname  ... date_of_birth soc_sec_id
rec-223-dup-0    jamilla     wallner  ...      19081209    6988048
rec-122-dup-0    lachlan       berry  ...      19990219    7364009
rec-373-dup-0     deakin  sondergeld  ...      19600210    2635962
rec-10-org         kayla  harrington  ...      19150612    9004242
rec-227-dup-0        mia      purdon  ...      19831024    8099933
...                  ...         ...  ...           ...        ...
rec-132-org       joshua      ingels  ...      19080503    3603864
rec-498-dup-0     claire       crook  ...           NaN    2161417
rec-8-org          james      jesser  ...      19120111    5961736
rec-222-dup-0     emiiyl     coleman  ...      19421221    7206933
rec-83-org      mitchell       berry  ...      19400503    2887622

[500 rows x 10 columns]

In [ ]:
right_df

given_name     surname  ... date_of_birth soc_sec_id
rec-223-org          NaN      waller  ...      19081209    6988048
rec-122-org      lachlan       berry  ...      19990219    7364009
rec-373-org       deakin  sondergeld  ...      19600210    2635962
rec-10-dup-0       kayla  harrington  ...      19150612    9004242
rec-227-org         luke      purdon  ...      19831024    8099933
...                  ...         ...  ...           ...        ...
rec-132-dup-0     joshua     ingelbs  ...      19080503    3603864
rec-498-org       claire       crook  ...           NaN    2161417
rec-8-dup-0        james     jeslser  ...      19120111    5961736
rec-222-org       emiily     coleman  ...      19421221    7206933
rec-83-dup-0    mitchell       berry  ...      19400503    2887622

[500 rows x 10 columns]

In [ ]:
left_df = left_df.drop(columns=['street_number', 'address_2', 'postcode', 'soc_sec_id'])
left_df.reset_index(level=0, inplace=True)
left_df

index given_name     surname  ...            suburb state date_of_birth
0    rec-223-dup-0    jamilla     wallner  ...          st james    wa      19081209
1    rec-122-dup-0    lachlan       berry  ...           bittern   qld      19990219
2    rec-373-dup-0     deakin  sondergeld  ...        canterbury   vic      19600210
3       rec-10-org      kayla  harrington  ...          coolaroo   nsw      19150612
4    rec-227-dup-0        mia      purdon  ...          gar butt   vic      19831024
..             ...        ...         ...  ...               ...   ...           ...
495    rec-132-org     joshua      ingels  ...      port lincoln   vic      19080503
496  rec-498-dup-0     claire       crook  ...               NaN   vic           NaN
497      rec-8-org      james      jesser  ...          st clair   vic      19120111
498  rec-222-dup-0     emiiyl     coleman  ...  wellington point   nsw      19421221
499     rec-83-org   mitchell       berry  ...        smithfield   nsw      19400503

[500 rows x 7 columns]

In [ ]:
right_df = right_df.drop(columns=['street_number', 'address_2', 'postcode', 'soc_sec_id'])
right_df.reset_index(level=0, inplace=True)
right_df

index given_name     surname  ...            suburb state date_of_birth
0      rec-223-org        NaN      waller  ...          st james    wa      19081209
1      rec-122-org    lachlan       berry  ...           bittern   qld      19990219
2      rec-373-org     deakin  sondergeld  ...        canterbury   vic      19600210
3     rec-10-dup-0      kayla  harrington  ...          coolaroo   nsw      19150612
4      rec-227-org       luke      purdon  ...           garbutt   vic      19831024
..             ...        ...         ...  ...               ...   ...           ...
495  rec-132-dup-0     joshua     ingelbs  ...      port lincoln   vic      19080503
496    rec-498-org     claire       crook  ...         wanniassa   vic           NaN
497    rec-8-dup-0      james     jeslser  ...          st clair   vic      19120111
498    rec-222-org     emiily     coleman  ...  wellington point   nsw      19421221
499   rec-83-dup-0   mitchell       berry  ...        smithfield   nsw      19400503

[500 rows x 7 columns]

In [ ]:
left_df_renamed =left_df.add_prefix('left_')

In [ ]:
right_df_renamed = right_df.add_prefix('right_')

In [ ]:
right_df_renamed['join'] = 1
right_df_renamed

right_index right_given_name  ... right_date_of_birth join
0      rec-223-org              NaN  ...            19081209    1
1      rec-122-org          lachlan  ...            19990219    1
2      rec-373-org           deakin  ...            19600210    1
3     rec-10-dup-0            kayla  ...            19150612    1
4      rec-227-org             luke  ...            19831024    1
..             ...              ...  ...                 ...  ...
495  rec-132-dup-0           joshua  ...            19080503    1
496    rec-498-org           claire  ...                 NaN    1
497    rec-8-dup-0            james  ...            19120111    1
498    rec-222-org           emiily  ...            19421221    1
499   rec-83-dup-0         mitchell  ...            19400503    1

[500 rows x 8 columns]

In [ ]:
left_df_renamed['join'] = 1
left_df_renamed

left_index left_given_name  ... left_date_of_birth join
0    rec-223-dup-0         jamilla  ...           19081209    1
1    rec-122-dup-0         lachlan  ...           19990219    1
2    rec-373-dup-0          deakin  ...           19600210    1
3       rec-10-org           kayla  ...           19150612    1
4    rec-227-dup-0             mia  ...           19831024    1
..             ...             ...  ...                ...  ...
495    rec-132-org          joshua  ...           19080503    1
496  rec-498-dup-0          claire  ...                NaN    1
497      rec-8-org           james  ...           19120111    1
498  rec-222-dup-0          emiiyl  ...           19421221    1
499     rec-83-org        mitchell  ...           19400503    1

[500 rows x 8 columns]

In [ ]:
final_df = pd.merge(left_df_renamed, right_df_renamed, on="join")
final_df.insert(0,'label',0)
final_df['combined_index'] = list(zip(final_df.left_index, final_df.right_index))
final_df.loc[final_df['combined_index'].isin(matching_dictionary),'label'] = 1
final_df = final_df.drop(columns=['join','left_index','right_index','combined_index'])
final_df

label left_given_name  ... right_state right_date_of_birth
0           1         jamilla  ...          wa            19081209
1           0         jamilla  ...         qld            19990219
2           0         jamilla  ...         vic            19600210
3           0         jamilla  ...         nsw            19150612
4           0         jamilla  ...         vic            19831024
...       ...             ...  ...         ...                 ...
249995      0        mitchell  ...         vic            19080503
249996      0        mitchell  ...         vic                 NaN
249997      0        mitchell  ...         vic            19120111
249998      0        mitchell  ...         nsw            19421221
249999      1        mitchell  ...         nsw            19400503

[250000 rows x 13 columns]

In [ ]:
final_df = final_df.sample(frac=1).reset_index(drop=True)

In [ ]:
import numpy as np
final_df = final_df[0:25000]
train,validate,test = np.split(final_df, [int(.8 * len(final_df)), int(.9 * len(final_df))])

In [ ]:
from google.colab import drive
drive.mount('/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /drive


In [ ]:
train_file = '/drive/My Drive/EntityMatching/train.csv'
validate_file = '/drive/My Drive/EntityMatching/validate.csv'
test_file = '/drive/My Drive/EntityMatching/test.csv'
train.to_csv(train_file)
validate.to_csv(validate_file)
test.to_csv(test_file)

In [ ]:
processed_train, processed_validate, processed_test = dm.data.process(path='.', train=train_file, validation=validate_file, test=test_file,ignore_columns=(''), left_prefix='left_',right_prefix='right_',label_attr='label',id_attr='id')


Reading and processing data from "/drive/My Drive/EntityMatching/train.csv"
0% [##############################] 100% | ETA: 00:00:00
Reading and processing data from "/drive/My Drive/EntityMatching/validate.csv"
0% [############################# ] 100% | ETA: 00:00:00
Reading and processing data from "/drive/My Drive/EntityMatching/test.csv"
0% [############################# ] 100% | ETA: 00:00:00INFO:deepmatcher.data.field:Downloading vectors from https://drive.google.com/uc?export=download&id=1Vih8gAmgBnuYDxfblbT94P6WjB7s1ZSh


downloading from Google Drive; may take a few minutes


wiki.en.bin: 8.49GB [03:07, 45.2MB/s]
INFO:deepmatcher.data.field:Extracting vectors into /root/.vector_cache

Building vocabulary
0% [####################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:01

Computing principal components
0% [####################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:06


In [ ]:
train_table = processed_train.get_raw_table()
train_table.head(10)

label left_given_name  ... right_state right_date_of_birth
0      0       stephanie  ...         vic            19790418
1      0          lauren  ...         nsw            19050716
2      0            jade  ...         act            19500629
3      0           caleb  ...          wa            19400306
4      0            alex  ...                        19861104
5      0          daniel  ...         qld            19621222
6      0         chelsea  ...         nsw            19860923
7      0             jad  ...         vic            19330624
8      0          morclm  ...         nsw            19241221
9      0          claire  ...         qld                    

[10 rows x 13 columns]

# New Section

In [ ]:
model = dm.MatchingModel(attr_summarizer='hybrid')

In [ ]:
model.run_train(
    processed_train,
    processed_validate,
    epochs=10,
    batch_size=16,
    best_save_path='hybrid_model.pth',
    pos_neg_ratio=3)

* Number of trainable parameters: 13363808
===>  TRAIN Epoch 1


/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:2352: UserWarning: reduction: 'mean' divides the total loss by both the batch size and the support size.'batchmean' divides only by the batch size, and aligns with the KL div math definition.'mean' will be changed to behave the same as 'batchmean' in the next major release.
  warnings.warn("reduction: 'mean' divides the total loss by both the batch size and the support size."
0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:05:39


Finished Epoch 1 || Run Time:  316.1 | Load Time:   24.0 || F1:  29.09 | Prec:  61.54 | Rec:  19.05 || Ex/s:  58.80

===>  EVAL Epoch 1


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:21


Finished Epoch 1 || Run Time:   18.6 | Load Time:    3.1 || F1:  33.33 | Prec: 100.00 | Rec:  20.00 || Ex/s: 114.79

* Best F1: tensor(33.3333, device='cuda:0')
Saving best model...
Done.
---------------------

===>  TRAIN Epoch 2


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:05:44


Finished Epoch 2 || Run Time:  321.0 | Load Time:   24.1 || F1:  82.67 | Prec:  93.94 | Rec:  73.81 || Ex/s:  57.97

===>  EVAL Epoch 2


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:21


Finished Epoch 2 || Run Time:   18.6 | Load Time:    3.1 || F1:  75.00 | Prec: 100.00 | Rec:  60.00 || Ex/s: 115.23

* Best F1: tensor(75., device='cuda:0')
Saving best model...
Done.
---------------------

===>  TRAIN Epoch 3


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:05:43


Finished Epoch 3 || Run Time:  319.7 | Load Time:   24.0 || F1:  91.14 | Prec:  97.30 | Rec:  85.71 || Ex/s:  58.18

===>  EVAL Epoch 3


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:21


Finished Epoch 3 || Run Time:   18.6 | Load Time:    3.1 || F1:  75.00 | Prec: 100.00 | Rec:  60.00 || Ex/s: 115.08

---------------------

===>  TRAIN Epoch 4


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:05:44


Finished Epoch 4 || Run Time:  320.6 | Load Time:   24.0 || F1:  93.67 | Prec: 100.00 | Rec:  88.10 || Ex/s:  58.03

===>  EVAL Epoch 4


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:21


Finished Epoch 4 || Run Time:   18.8 | Load Time:    3.2 || F1:  75.00 | Prec: 100.00 | Rec:  60.00 || Ex/s: 113.82

---------------------

===>  TRAIN Epoch 5


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:05:42


Finished Epoch 5 || Run Time:  318.7 | Load Time:   23.9 || F1:  95.24 | Prec:  95.24 | Rec:  95.24 || Ex/s:  58.38

===>  EVAL Epoch 5


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:21


Finished Epoch 5 || Run Time:   18.4 | Load Time:    3.1 || F1: 100.00 | Prec: 100.00 | Rec: 100.00 || Ex/s: 116.15

* Best F1: tensor(100., device='cuda:0')
Saving best model...
Done.
---------------------

===>  TRAIN Epoch 6


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:05:39


Finished Epoch 6 || Run Time:  315.9 | Load Time:   23.9 || F1:  97.62 | Prec:  97.62 | Rec:  97.62 || Ex/s:  58.86

===>  EVAL Epoch 6


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:21


Finished Epoch 6 || Run Time:   18.6 | Load Time:    3.2 || F1:  88.89 | Prec: 100.00 | Rec:  80.00 || Ex/s: 114.88

---------------------

===>  TRAIN Epoch 7


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:05:45


Finished Epoch 7 || Run Time:  321.3 | Load Time:   24.1 || F1:  97.62 | Prec:  97.62 | Rec:  97.62 || Ex/s:  57.91

===>  EVAL Epoch 7


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:21


Finished Epoch 7 || Run Time:   18.6 | Load Time:    3.2 || F1:  88.89 | Prec: 100.00 | Rec:  80.00 || Ex/s: 114.60

---------------------

===>  TRAIN Epoch 8


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:05:42


Finished Epoch 8 || Run Time:  319.0 | Load Time:   24.0 || F1: 100.00 | Prec: 100.00 | Rec: 100.00 || Ex/s:  58.32

===>  EVAL Epoch 8


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:21


Finished Epoch 8 || Run Time:   18.7 | Load Time:    3.1 || F1:  88.89 | Prec: 100.00 | Rec:  80.00 || Ex/s: 114.40

---------------------

===>  TRAIN Epoch 9


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:05:45


Finished Epoch 9 || Run Time:  321.6 | Load Time:   24.2 || F1: 100.00 | Prec: 100.00 | Rec: 100.00 || Ex/s:  57.84

===>  EVAL Epoch 9


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:21


Finished Epoch 9 || Run Time:   18.5 | Load Time:    3.1 || F1:  75.00 | Prec: 100.00 | Rec:  60.00 || Ex/s: 115.31

---------------------

===>  TRAIN Epoch 10


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:05:46


Finished Epoch 10 || Run Time:  322.8 | Load Time:   24.2 || F1: 100.00 | Prec: 100.00 | Rec: 100.00 || Ex/s:  57.63

===>  EVAL Epoch 10


0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:21


Finished Epoch 10 || Run Time:   18.5 | Load Time:    3.1 || F1:  88.89 | Prec: 100.00 | Rec:  80.00 || Ex/s: 115.57

---------------------

Loading best model...
Training done.


tensor(100., device='cuda:0')

In [ ]:
model.run_eval(processed_test)

===>  EVAL Epoch 5


0% [███████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:11


Finished Epoch 5 || Run Time:    9.4 | Load Time:    2.8 || F1:  93.33 | Prec: 100.00 | Rec:  87.50 || Ex/s: 204.30



tensor(93.3333, device='cuda:0')

In [ ]:
# Comparison for recordlinkage methods
compare_cl = recordlinkage.Compare()
compare_cl.exact('given_name', 'given_name', label='given_name')
compare_cl.string('surname', 'surname', method='jarowinkler', threshold=0.85, label='surname')
compare_cl.exact('date_of_birth', 'date_of_birth', label='date_of_birth')
compare_cl.exact('suburb', 'suburb', label='suburb')
compare_cl.exact('state', 'state', label='state')
compare_cl.string('address_1', 'address_1', threshold=0.85, label='address_1')

<Compare>

In [ ]:
# Load data
true_links = {}
features = {}
validation = {}
datasets= {'train':train_file, 
'test':test_file,
'validation':validate_file}

for key in datasets:
    df = pd.read_csv(datasets[key])
    nof_cols = int((df.shape[1] - 2)/2)
    dfA = df.iloc[:,2:nof_cols + 2]
    dfB = df.iloc[:,nof_cols + 2:df.shape[1]]
    dfA.rename(columns={c:c[5:] for c in dfA.columns },inplace=True)
    dfB.rename(columns={c:c[6:] for c in dfB.columns },inplace=True)

    tuples = [(i,i) for i in range(len(df)) if df.iloc[i]['label'] == 1]
    true_links[key] = pd.MultiIndex.from_tuples(tuples)

    tuples_full = [(i,i) for i in range(len(df))]
    candidate_links = pd.MultiIndex.from_tuples(tuples_full)
    # Final features (used in all methods)
    features[key] = compare_cl.compute(candidate_links, dfA, dfB)

In [ ]:
# Some helper functions
def print_results(name, table):
    print("".join(['*' for x in range(len(name) + 1)]))
    print('{}'.format(name))
    print("".join(['*' for x in range(len(name) + 1)]))
    print("Confusion matrix:")
    print(table['confusion_matrix'])
    print("Accuracy: {}".format(table['accuracy']))
    print("Precision: {}".format(table['precision']))
    print("Recall: {}".format(table['recall']))
    print("F-score: {}".format(table['f-score']))
    print('\n')
    
def performance_metrics(true_links, result, set_size):
    validation = {}
    validation['confusion_matrix'] = recordlinkage.confusion_matrix(true_links, result, set_size)
    validation['accuracy'] = recordlinkage.accuracy(true_links, result, len(features['validation']))
    validation['precision'] = recordlinkage.precision(true_links, result)
    validation['recall'] = recordlinkage.recall(true_links, result)
    validation['f-score'] = recordlinkage.fscore(true_links, result)
    return validation

In [ ]:
# Train and validate various classifiers
classifiers= {
'Hand-tuned':None,
'Logistic regression':recordlinkage.LogisticRegressionClassifier(),
'Naive Bayes': recordlinkage.NaiveBayesClassifier(),
'Support vector machine': recordlinkage.SVMClassifier(),
'K-means': recordlinkage.KMeansClassifier(),
'ECM': recordlinkage.ECMClassifier()}

for key in classifiers:
    validation[key] = {}
    if key == 'Hand-tuned':
        # Immediate prediction
        result = features['validation'][features['validation'].sum(axis=1) > 3].index
    else:
        # Training 
        if key == 'ECM':
            classifiers[key].fit(features['train']) # somehow ECM cannot ignore redundant argument, opposed to K-Means
        else:
            classifiers[key].fit(features['train'], true_links['train'])
        # Predict the match status for all test record pairs
        result =  classifiers[key].predict(features['validation'])
        
    # Validate
    validation[key] = performance_metrics(true_links['validation'], result, len(features['validation']))
    
    #Print results
    print_results(key, validation[key])

***********
Hand-tuned
***********
Confusion matrix:
[[   4    1]
 [   0 2495]]
Accuracy: 0.9996
Precision: 1.0
Recall: 0.8
F-score: 0.888888888888889


********************
Logistic regression
********************
Confusion matrix:
[[   4    1]
 [   0 2495]]
Accuracy: 0.9996
Precision: 1.0
Recall: 0.8
F-score: 0.888888888888889


************
Naive Bayes
************
Confusion matrix:
[[   5    0]
 [   0 2495]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F-score: 1.0


***********************
Support vector machine
***********************
Confusion matrix:
[[   5    0]
 [   0 2495]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F-score: 1.0


********
K-means
********
Confusion matrix:
[[   5    0]
 [   0 2495]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F-score: 1.0


****
ECM
****
Confusion matrix:
[[   5    0]
 [   0 2495]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F-score: 1.0




In [ ]:
# Test results for best method
f_scores = {key:validation[key]['f-score'] for key in validation}
best_model = max(f_scores, key = f_scores.get) 
if best_model == 'Hand-tuned':
    result = features['test'][features['test'].sum(axis=1) > 2].index
else:
    result = classifiers[best_model].predict(features['test'])
test =  performance_metrics(true_links['test'], result, len(features['test']))
print_results("Selected model ({}) on test set".format(best_model), test)

*****************************************
Selected model (Naive Bayes) on test set
*****************************************
Confusion matrix:
[[   8    0]
 [   0 2492]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F-score: 1.0


